import type { Metadata } from "next";
import { K2D, Inter} from "next/font/google";
import Navbar from "./components/Navbar";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const k2d = K2D({
  subsets:["latin"],
  weight: ["200","400","500","600"],
  variable: "--font-k2d",
  display: "swap",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${k2d.variable}`}>
        {children}
        <Navbar/> 
      </body>
    </html>
  );
}
